default: styles/application.scss
blue: styles/application_blue.scss
green: styles/application_green.scss
dark-green: styles/application_dark-green.scss
chocolate: styles/application_chocolate.scss
purple: styles/application_purple.scss
light-grey: styles/application_light-grey.scss
light-blue: styles/application_light-blue.scss
pink: styles/application_pink.scss
yellow: styles/application_yellow.scss
white: styles/application_white.scss
contrast: styles/contrast.scss
